# Generated by Django 5.1.5 on 2025-02-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_ride_options_park_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={},
        ),
        migrations.RemoveField(
            model_name='ride',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='park',
        ),
        migrations.AddField(
            model_name='ride',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
